#!/bin/bash
containerName=boobank-app

if [ $1 = "start" ] 
then
    echo "Starting the containers..."
    docker-compose down
    docker-compose up --build --force-recreate
elif [ $1 = "build" ]
then
    echo "Closing the old containers..."
    docker-compose down

    echo "Building the containers..."
    docker-compose build --no-cache
    docker-compose up --force-recreate
else
    echo "Unknown command?"
fi
